//! Generated byte-exact string-cut and stored-extra-order regressions.

use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use pm_rust::{ItemFilter, ListOptions, Workspace};
use serde_json::Value;
use std::fmt::Write as _;
use std::{fs, path::Path, process::Command};

#[path = "support/published_cli.rs"]
mod published_cli;

const CLOCK: &str = "2026-10-02T10:00:00.000Z";
type TestResult = Result<(), Box<dyn std::error::Error>>;

/// Installs a fixed-clock driver over the locked, real published executable.
fn fixture() -> Result<tempfile::TempDir, Box<dyn std::error::Error>> {
    let directory = tempfile::tempdir()?;
    let root = directory.path().join(".agents/pm");
    fs::create_dir_all(root.join("tasks"))?;
    let mut settings: Value = serde_json::from_str(include_str!("fixtures/list-settings.json"))?;
    settings["telemetry"]["enabled"] = Value::Bool(false);
    fs::write(root.join("settings.json"), settings.to_string())?;
    if let Some(published) = published_cli::published_cli_or_skip("output parity differential") {
        let package: Value =
            serde_json::from_slice(&fs::read(published.package_root.join("package.json"))?)?;
        assert_eq!(package["version"], "2026.10.7");
        fs::write(
            directory.path().join("driver.mjs"),
            format!(
                "import {{pathToFileURL}} from 'node:url';const fixed=Date.parse({});const OriginalDate=Date;globalThis.Date=class extends OriginalDate {{constructor(...args){{args.length?super(...args):super(fixed)}}static now(){{return fixed}}}};process.argv=[process.argv[0],'pm',...process.argv.slice(2)];await import(pathToFileURL({}));",
                serde_json::to_string(CLOCK)?,
                serde_json::to_string(&published.entry)?
            ),
        )?;
    }
    Ok(directory)
}

/// Stores independently generated title, description and extra metadata.
fn item(
    directory: &Path,
    index: usize,
    title: &str,
    description: &str,
    extras: &str,
) -> TestResult {
    let id = format!("demo-{index:04}");
    fs::write(
        directory
            .join(".agents/pm/tasks")
            .join(format!("{id}.toon")),
        format!(
            "id: {id}\ntitle: {}\ndescription: {}\ntype: Task\nstatus: open\npriority: 2\ntags: []\ncreated_at: \"2026-09-01T00:00:00.000Z\"\nupdated_at: \"2026-09-01T00:00:00.000Z\"\n{extras}body: \"\"\n",
            serde_json::to_string(title)?,
            serde_json::to_string(description)?
        ),
    )?;
    Ok(())
}

/// Compares complete stdout, stderr and exit code, plus both SDK serializers.
fn compare(
    directory: &Path,
    budget: &str,
    intent: bool,
    amount: Option<&str>,
    cursor: Option<&str>,
) -> Result<pm_rust::ListOutput, Box<dyn std::error::Error>> {
    let mut flags = vec![
        "list",
        "--json",
        "--full",
        "--output-limit",
        amount.unwrap_or("unbounded"),
        "--output-budget",
        budget,
    ];
    if intent {
        flags.extend(["--for", "triage", "--token-budget", "120000"]);
    }
    if let Some(cursor) = cursor {
        flags.extend(["--output-cursor", cursor]);
    }
    let native = Command::new(env!("CARGO_BIN_EXE_pm-rust"))
        .args(&flags)
        .args(["--timestamp", CLOCK])
        .current_dir(directory)
        .env_remove("PM_PATH")
        .output()?;
    assert!(
        native.status.success(),
        "native: {}",
        String::from_utf8_lossy(&native.stderr)
    );
    let native_text = std::str::from_utf8(&native.stdout)?;
    if directory.join("driver.mjs").is_file() {
        let oracle = Command::new(
            std::env::var("PM_NODE_INTERPRETER").unwrap_or_else(|_| "node".to_owned()),
        )
        .arg(directory.join("driver.mjs"))
        .args(&flags)
        .current_dir(directory)
        .env_remove("PM_PATH")
        .output()?;
        assert_eq!(native.status.code(), oracle.status.code());
        assert_eq!(native.stderr, oracle.stderr);
        let oracle_text = std::str::from_utf8(&oracle.stdout)?;
        let mismatch = native
            .stdout
            .iter()
            .zip(&oracle.stdout)
            .position(|(a, b)| a != b)
            .unwrap_or(native.stdout.len().min(oracle.stdout.len()));
        assert!(
            native_text == oracle_text,
            "budget {budget}, intent {intent}; first mismatch byte {mismatch}: native {:?}, oracle {:?}",
            String::from_utf8_lossy(
                &native.stdout[mismatch..native.stdout.len().min(mismatch + 40)]
            ),
            String::from_utf8_lossy(
                &oracle.stdout[mismatch..oracle.stdout.len().min(mismatch + 40)]
            )
        );
    }
    let sdk = Workspace::discover(directory)?.list_page(
        &ItemFilter::default(),
        &ListOptions {
            full: true,
            output_limit: Some(amount.unwrap_or("unbounded").to_owned()),
            output_cursor: cursor.map(str::to_owned),
            output_budget: Some(budget.to_owned()),
            intent: intent.then(|| "triage".to_owned()),
            token_budget: intent.then(|| "120000".to_owned()),
            ..ListOptions::default()
        },
        CLOCK,
    )?;
    assert_eq!(
        native_text,
        format!("{}\n", pm_rust::stringify_json(&sdk, true))
    );
    let mut wire = Vec::new();
    pm_rust::write_pretty_json(&mut wire, &sdk)?;
    assert_eq!(native_text, format!("{}\n", std::str::from_utf8(&wire)?));
    // serde's JSON serializer must preserve the escaped code unit too.
    assert_eq!(
        serde_json::to_string(&sdk)?,
        pm_rust::stringify_json(&sdk, false)
    );
    Ok(sdk)
}

/// Four astral characters start at every UTF-16 offset around the 240-unit cut.
#[test]
fn generated_utf16_cut_offsets_match_locked_oracle() -> TestResult {
    let directory = fixture()?;
    for offset in 0..=241 {
        let text = |astral| format!("{}{astral}{}", "x".repeat(offset), "x".repeat(2000));
        let extras = format!(
            "astral: {}\nnested:\n  slash/key~[1]:\n    - {}\nliteral: \"�\\\\ud83d\"\n",
            serde_json::to_string(&text('𝄞'))?,
            serde_json::to_string(&text('𠀀'))?
        );
        item(directory.path(), offset, &text('😀'), &text('𐐷'), &extras)?;
    }
    for intent in [false, true] {
        let result = compare(directory.path(), "120000", intent, None, None)?;
        assert_eq!(result["count"], 242);
        assert_eq!(result["read_output"]["strings_compacted"], !intent);
        assert_eq!(result["read_output"]["rows_compacted"], false);
        let wire = pm_rust::stringify_json(&result, true);
        for escape in ["\\ud83d…", "\\ud801…", "\\ud834…", "\\ud840…"] {
            assert_eq!(wire.matches(escape).count(), 1, "{escape}");
        }
        assert_eq!(
            wire.matches("�\\\\ud83d").count(),
            242,
            "literal strings must not be interpreted as cuts"
        );
        assert_eq!(
            result["read_output"]["estimated_tokens"],
            (wire.len() + 1).div_ceil(4)
        );
        if intent {
            assert_eq!(
                result["context_intent"]["estimated_tokens"],
                pm_rust::stringify_json(&result, false).len().div_ceil(4)
            );
        }
    }
    // Intent compaction precedes canonical amount/cost controls. Replay must
    // rebase lossless pointers and hash the escaped strings, not the safe view.
    let first = compare(directory.path(), "3000", true, None, None)?;
    let cursor = first["next_cursor"]
        .as_str()
        .ok_or("missing output continuation")?;
    let second = compare(directory.path(), "3000", true, None, Some(cursor))?;
    assert!(second["count"].as_u64().is_some_and(|count| count > 0));
    let mut last_cursor: Value = serde_json::from_slice(&URL_SAFE_NO_PAD.decode(cursor)?)?;
    last_cursor["o"] = serde_json::json!(239);
    let last_cursor = URL_SAFE_NO_PAD.encode(last_cursor.to_string());
    let tail = compare(directory.path(), "120000", true, None, Some(&last_cursor))?;
    assert_eq!(tail["count"], 3);
    for escape in ["\\ud83d…", "\\ud801…", "\\ud834…", "\\ud840…"] {
        assert_eq!(
            pm_rust::stringify_json(&tail, true).matches(escape).count(),
            1
        );
    }
    let capped = compare(directory.path(), "120000", true, Some("2"), None)?;
    assert_eq!(capped["count"], 2);
    println!(
        "verified 968 generated astral placements, plain and triage, plus literal replacement/escape strings"
    );
    Ok(())
}

/// Enumerates every ordering of four unknown keys, including nested objects.
#[test]
fn generated_extra_key_permutations_match_locked_oracle() -> TestResult {
    let directory = fixture()?;
    let keys = ["zebra", "budget", "alpha", "middle"];
    let mut index = 0;
    for a in 0..4 {
        for b in 0..4 {
            for c in 0..4 {
                for d in 0..4 {
                    let order = [a, b, c, d];
                    if order
                        .iter()
                        .enumerate()
                        .any(|(i, key)| order[..i].contains(key))
                    {
                        continue;
                    }
                    let mut extras = String::new();
                    for key in order {
                        writeln!(extras, "{}:\n  z: 30.125\n  a: 0.000001", keys[key])?;
                    }
                    item(directory.path(), index, "Metadata order", "", &extras)?;
                    index += 1;
                }
            }
        }
    }
    assert_eq!(index, 24);
    for budget in ["unbounded", "100000"] {
        let result = compare(directory.path(), budget, false, None, None)?;
        assert_eq!(result["count"], 24);
    }
    println!("verified all 24 extra-key permutations with nested key order and JS numbers");
    Ok(())
}
